/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { MaintenanceListRelationFilter } from "../../maintenance/base/MaintenanceListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { TripHistoryListRelationFilter } from "../../tripHistory/base/TripHistoryListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

@InputType()
class VehicleWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MaintenanceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MaintenanceListRelationFilter)
  @IsOptional()
  @Field(() => MaintenanceListRelationFilter, {
    nullable: true,
  })
  maintenances?: MaintenanceListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  manufacturer?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  model?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  plateNumber?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TripHistoryListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TripHistoryListRelationFilter)
  @IsOptional()
  @Field(() => TripHistoryListRelationFilter, {
    nullable: true,
  })
  tripHistories?: TripHistoryListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  year?: IntNullableFilter;
}

export { VehicleWhereInput as VehicleWhereInput };
