/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TripHistoryService } from "../tripHistory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TripHistoryCreateInput } from "./TripHistoryCreateInput";
import { TripHistory } from "./TripHistory";
import { TripHistoryFindManyArgs } from "./TripHistoryFindManyArgs";
import { TripHistoryWhereUniqueInput } from "./TripHistoryWhereUniqueInput";
import { TripHistoryUpdateInput } from "./TripHistoryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TripHistoryControllerBase {
  constructor(
    protected readonly service: TripHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TripHistory })
  @nestAccessControl.UseRoles({
    resource: "TripHistory",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTripHistory(
    @common.Body() data: TripHistoryCreateInput
  ): Promise<TripHistory> {
    return await this.service.createTripHistory({
      data: {
        ...data,

        driver: data.driver
          ? {
              connect: data.driver,
            }
          : undefined,

        vehicle: data.vehicle
          ? {
              connect: data.vehicle,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        destination: true,

        driver: {
          select: {
            id: true,
          },
        },

        endTime: true,
        id: true,
        origin: true,
        startTime: true,
        updatedAt: true,

        vehicle: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TripHistory] })
  @ApiNestedQuery(TripHistoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TripHistory",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async tripHistories(@common.Req() request: Request): Promise<TripHistory[]> {
    const args = plainToClass(TripHistoryFindManyArgs, request.query);
    return this.service.tripHistories({
      ...args,
      select: {
        createdAt: true,
        destination: true,

        driver: {
          select: {
            id: true,
          },
        },

        endTime: true,
        id: true,
        origin: true,
        startTime: true,
        updatedAt: true,

        vehicle: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TripHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TripHistory",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async tripHistory(
    @common.Param() params: TripHistoryWhereUniqueInput
  ): Promise<TripHistory | null> {
    const result = await this.service.tripHistory({
      where: params,
      select: {
        createdAt: true,
        destination: true,

        driver: {
          select: {
            id: true,
          },
        },

        endTime: true,
        id: true,
        origin: true,
        startTime: true,
        updatedAt: true,

        vehicle: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TripHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TripHistory",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTripHistory(
    @common.Param() params: TripHistoryWhereUniqueInput,
    @common.Body() data: TripHistoryUpdateInput
  ): Promise<TripHistory | null> {
    try {
      return await this.service.updateTripHistory({
        where: params,
        data: {
          ...data,

          driver: data.driver
            ? {
                connect: data.driver,
              }
            : undefined,

          vehicle: data.vehicle
            ? {
                connect: data.vehicle,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          destination: true,

          driver: {
            select: {
              id: true,
            },
          },

          endTime: true,
          id: true,
          origin: true,
          startTime: true,
          updatedAt: true,

          vehicle: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TripHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TripHistory",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTripHistory(
    @common.Param() params: TripHistoryWhereUniqueInput
  ): Promise<TripHistory | null> {
    try {
      return await this.service.deleteTripHistory({
        where: params,
        select: {
          createdAt: true,
          destination: true,

          driver: {
            select: {
              id: true,
            },
          },

          endTime: true,
          id: true,
          origin: true,
          startTime: true,
          updatedAt: true,

          vehicle: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
